#server:
#  port: 9910
  
manifest:
  base-uri:
  username: udeploy_api
  password: udeployritut25gtlaitrqecg
   
udeploy:
  app-name: INTERATIONDELETELISTENER
  component-name: INTETACTION
  resource-group: ECDC
  team: CVM
  resource-map:
    L1:
      - c0008914.test.cloud.fedex.com
      - c0008915.test.cloud.fedex.com
      - c0008916.test.cloud.fedex.com
      - c0008917.test.cloud.fedex.com      
    L2:
      - c0005195.test.cloud.fedex.com
      - c0009462.test.cloud.fedex.com
      - c0009463.test.cloud.fedex.com
      - c0005377.test.cloud.fedex.com
    L3: 
      - c0010256.test.cloud.fedex.com
      - c0010257.test.cloud.fedex.com
      - c0010258.test.cloud.fedex.com
      - c0010259.test.cloud.fedex.com
    L4:
      - c0010546.test.cloud.fedex.com
      - c0010547.test.cloud.fedex.com
      - c0010548.test.cloud.fedex.com
      - c0010549.test.cloud.fedex.com
      - c0010550.test.cloud.fedex.com
      - c0010551.test.cloud.fedex.com
      - c0010551.test.cloud.fedex.com
      - c0010552.test.cloud.fedex.com
      - c0010553.test.cloud.fedex.com
      - c0010554.test.cloud.fedex.com
      - c0010555.test.cloud.fedex.com
      - c0010556.test.cloud.fedex.com
      - c0010557.test.cloud.fedex.com
