server:
  port: 9899

manifest:
  base-url: http://udeploy.test.cloud.fedex.com:8080
  create-tag-uri: /cli/resource/tag
  check-team-uri: /cli/team/info
  create-uri: /cli/resource/create 
  check-resource-uri: /cli/resource
  create-team-uri: /cli/agentCLI/teams
  username: ${username}
  password: ${password} 
#  username: udeploy_api
#  password: udeployritut25gtlaitrqecg
