server:
  port: 9899
  
swagger:
  title: uDeploy Spring Boot API
  version: 1.0
  description: Spring Boot UDeploy Client App
  base-package: snmaddula.udeploy.app.controller
  contact-name: Vaishnavi
  contact-url:  
  contact-email: abc@gmail.com
  
manifest:
  base-uri: https://udeploy2-wtc.prod.cloud.fedex.com:6371
  info-uri: 
  create-uri: /cli/resource/create 
  add-tag: /cli/resource/tag
     
   