server:
  port: 9899

manifest:
  base-url: http://udeploy.test.cloud.fedex.com:8080
  create-tag-uri: /cli/resource/tag
  check-team-uri: /cli/team/info
  check-resource-uri: /cli/resource
  create-resource-uri: /cli/resource/create 
  create-team-uri: /cli/agentCLI/teams
  create-component-uri: /cli/component/create
  create-application-uri: /cli/application/create
  create-environment-uri: /cli/environment/createEnvironment
  username: ${username}
  password: ${password} 
#  username: udeploy_api
#  password: udeployritut25gtlaitrqecg
